name: example
description: Internationalization example
version: 1.0.0+1

environment:
  sdk: ">=2.6.0-dev <3.0.0"

dependencies:
  i18n_extension:
    path: ../
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
